export const RoleEnum = {
  CUSTOMER: 'CUSTOMER',
  EXPERT: 'EXPERT',
  ADMIN: 'ADMIN',
} as const;

export type RoleType = keyof typeof RoleEnum;

export const Permissions = {
  // Common
  VIEW_PROFILE: 'VIEW_PROFILE',
  EDIT_PROFILE: 'EDIT_PROFILE',
  VIEW_LISTINGS: 'VIEW_LISTINGS',
  SEND_MESSAGE: 'SEND_MESSAGE',
  VIEW_REVIEWS: 'VIEW_REVIEWS',

  // Customer-only
  BOOK_SERVICE: 'BOOK_SERVICE',
  MAKE_PAYMENT: 'MAKE_PAYMENT',
  RATE_EXPERT: 'RATE_EXPERT',

  // Expert-only
  CREATE_LISTING: 'CREATE_LISTING',
  EDIT_LISTING: 'EDIT_LISTING',
  DELETE_LISTING: 'DELETE_LISTING',
  VIEW_BOOKINGS: 'VIEW_BOOKINGS',
  ACCEPT_BOOKING: 'ACCEPT_BOOKING',
  REJECT_BOOKING: 'REJECT_BOOKING',

  // Admin-only
  VERIFY_USER: 'VERIFY_USER',
  VIEW_ALL_USERS: 'VIEW_ALL_USERS',
  DELETE_USER: 'DELETE_USER',
  ACCESS_ANALYTICS: 'ACCESS_ANALYTICS',
  MANAGE_PAYMENTS: 'MANAGE_PAYMENTS',
  RESOLVE_DISPUTE: 'RESOLVE_DISPUTE',
  SEND_NOTIFICATION: 'SEND_NOTIFICATION',
} as const;

export type PermissionType = keyof typeof Permissions;
